"""create role tables

Revision ID: 207ef1efca8c
Revises: d4bf49562258
Create Date: 2024-09-19 01:58:08.985103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '207ef1efca8c'
down_revision: Union[str, None] = 'd4bf49562258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index('idx_role_name', 'role', ['name'], unique=True, schema='users')
    op.create_index(op.f('ix_users_role_id'), 'role', ['id'], unique=False, schema='users')
    op.create_table('user_role',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index('idx_user_role_role_id', 'user_role', ['role_id'], unique=False, schema='users')
    op.create_index('idx_user_role_user_id', 'user_role', ['user_id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_user_role_id'), 'user_role', ['id'], unique=False, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_role_id'), table_name='user_role', schema='users')
    op.drop_index('idx_user_role_user_id', table_name='user_role', schema='users')
    op.drop_index('idx_user_role_role_id', table_name='user_role', schema='users')
    op.drop_table('user_role', schema='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='role', schema='users')
    op.drop_index('idx_role_name', table_name='role', schema='users')
    op.drop_table('role', schema='users')
    # ### end Alembic commands ###
