"""create product review table

Revision ID: ac5cd3a9677e
Revises: f7864cd5c20e
Create Date: 2024-09-19 02:03:16.647446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac5cd3a9677e'
down_revision: Union[str, None] = 'f7864cd5c20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='products'
    )
    op.create_index('idx_review_product_id', 'review', ['product_id'], unique=False, schema='products')
    op.create_index('idx_review_user_id', 'review', ['user_id'], unique=False, schema='products')
    op.create_index(op.f('ix_products_review_id'), 'review', ['id'], unique=False, schema='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_review_id'), table_name='review', schema='products')
    op.drop_index('idx_review_user_id', table_name='review', schema='products')
    op.drop_index('idx_review_product_id', table_name='review', schema='products')
    op.drop_table('review', schema='products')
    # ### end Alembic commands ###
