"""create order tables

Revision ID: 2049d9a0e4ae
Revises: e20e9a8d027f
Create Date: 2024-09-19 02:06:03.506345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2049d9a0e4ae'
down_revision: Union[str, None] = 'e20e9a8d027f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', 'REJECTED', 'SHIPPED', 'DELIVERED', 'RETURNED', 'CONFIRMED', name='order_status', schema='orders'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index('idx_order_user_id', 'order', ['user_id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_order_id'), 'order', ['id'], unique=False, schema='orders')
    op.create_table('order_item',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['users.user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index('idx_order_item_order_id', 'order_item', ['order_id'], unique=False, schema='orders')
    op.create_index('idx_order_item_product_id', 'order_item', ['product_id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_order_item_id'), 'order_item', ['id'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_item_id'), table_name='order_item', schema='orders')
    op.drop_index('idx_order_item_product_id', table_name='order_item', schema='orders')
    op.drop_index('idx_order_item_order_id', table_name='order_item', schema='orders')
    op.drop_table('order_item', schema='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='order', schema='orders')
    op.drop_index('idx_order_user_id', table_name='order', schema='orders')
    op.drop_table('order', schema='orders')
    sa.Enum(name='order_status', schema='orders').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
