"""create product category table

Revision ID: 54787acbe88a
Revises: 1ec3a92562a6
Create Date: 2024-09-19 02:01:05.812843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54787acbe88a'
down_revision: Union[str, None] = '1ec3a92562a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS products')
    op.create_table('category',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='products'
    )
    op.create_index('idx_category_name', 'category', ['name'], unique=True, schema='products')
    op.create_index(op.f('ix_products_category_id'), 'category', ['id'], unique=False, schema='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_category_id'), table_name='category', schema='products')
    op.drop_index('idx_category_name', table_name='category', schema='products')
    op.drop_table('category', schema='products')
    op.execute("DROP SCHEMA IF EXISTS products CASCADE")
    # ### end Alembic commands ###
